#Expyriment 0.10.0 (Python 3.7.16), .xpe-file, coding: cp1252
#date: Tue Apr 30 2024 09:44:16
#sha1: 576e47
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Windows', node='T2', release='10', version='10.0.22621', machine='AMD64', processor='Intel64 Family 6 Model 122 Stepping 1, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
312,stdout,received,'0 0'
2550,design,log,
#design: #exp: Hsu task
#design: block_cnt,block_id,trial_cnt,trial_id
2550,design,logged,
2550,Experiment,started
2550,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_jom6jweq\\freq1046_dur150.0_d5vjj4bh.wav'
4701,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_jom6jweq\\freq1975_dur50.0_jzyv4p2m.wav'
4701,stdout,received,'0 1'
4730,stderr,received,'Traceback (most recent call last):'
4730,stderr,received,'  File "code.py", line 86, in <module>'
4733,stderr,received,'    run_trial(cue_freq, SOA, target_freq)'
4733,stderr,received,'  File "code.py", line 73, in run_trial'
4734,stderr,received,'    expyriment.control.start()'
4734,stderr,received,'  File "C:\\Users\\manon\\anaconda3\\envs\\expyriment\\lib\\site-packages\\expyriment\\control\\_experiment_control.py", line 73, in start'
4734,stderr,received,'    raise Exception("Experiment is already started!")'
4735,stderr,received,'Exception: Experiment is already started!'
