#Expyriment 0.10.0 (Python 3.7.16), .xpe-file, coding: cp1252
#date: Wed May 01 2024 10:28:34
#sha1: 463817
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Windows', node='T2', release='10', version='10.0.22621', machine='AMD64', processor='Intel64 Family 6 Model 122 Stepping 1, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
402,Stimulus,presented,0
4853,design,log,
#design: #exp: Hsu task
#design: #dvn: Cue,SOA,target,key,response time
#design: block_cnt,block_id,trial_cnt,trial_id
4853,design,logged,
4853,Experiment,started
4853,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_btli5tyb\\freq1318_dur150.0_n4h4h6vd.wav'
6104,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_btli5tyb\\freq1975_dur50.0_xggv8ewx.wav'
7427,Keyboard,received,13,wait
7487,stderr,received,'Traceback (most recent call last):'
7487,stderr,received,'  File "code.py", line 98, in <module>'
7488,stderr,received,'    run_trial(cue_freq, SOA, target_freq)'
7489,stderr,received,'  File "code.py", line 80, in run_trial'
7489,stderr,received,'    expyriment.control.start()'
7490,stderr,received,'  File "C:\\Users\\manon\\anaconda3\\envs\\expyriment\\lib\\site-packages\\expyriment\\control\\_experiment_control.py", line 73, in start'
7491,stderr,received,'    raise Exception("Experiment is already started!")'
7492,stderr,received,'Exception: Experiment is already started!'
7497,Data,saved
