#Expyriment 0.10.0 (Python 3.7.16), .xpe-file, coding: cp1252
#date: Wed May 01 2024 10:26:32
#sha1: 2763af
#modules: 
#display: size=(800, 600), window_mode=True, open_gl=2
#os: uname_result(system='Windows', node='T2', release='10', version='10.0.22621', machine='AMD64', processor='Intel64 Family 6 Model 122 Stepping 1, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
350,Stimulus,presented,0
6069,design,log,
#design: #exp: Hsu task
#design: #dvn: Cue,SOA,target,key,response time
#design: block_cnt,block_id,trial_cnt,trial_id
6069,design,logged,
6069,Experiment,started
6069,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_beea76js\\freq1318_dur150.0_enrlamfo.wav'
7319,Stimulus,played,b'C:\\Users\\manon\\AppData\\Local\\Temp\\expyriment_beea76js\\freq2025_dur50.0_8bnu9dwk.wav'
7392,Keyboard,received,13,wait
7451,stderr,received,'Traceback (most recent call last):'
7451,stderr,received,'  File "code.py", line 98, in <module>'
7452,stderr,received,'    run_trial(cue_freq, SOA, target_freq)'
7452,stderr,received,'  File "code.py", line 80, in run_trial'
7453,stderr,received,'    expyriment.control.start()'
7453,stderr,received,'  File "C:\\Users\\manon\\anaconda3\\envs\\expyriment\\lib\\site-packages\\expyriment\\control\\_experiment_control.py", line 73, in start'
7460,stderr,received,'    raise Exception("Experiment is already started!")'
7461,stderr,received,'Exception: Experiment is already started!'
7466,Data,saved
